-- MySQL Script generated by MySQL Workbench
-- Sun Nov  3 18:34:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aset_dkrth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aset_dkrth` ;

-- -----------------------------------------------------
-- Schema aset_dkrth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aset_dkrth` DEFAULT CHARACTER SET utf8 ;
USE `aset_dkrth` ;

-- -----------------------------------------------------
-- Table `aset_dkrth`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`user` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`user` (
  `id_user` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  `telepon` INT NULL,
  `roles` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`bidang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`bidang` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`bidang` (
  `id_bidang` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id_bidang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`kegiatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`kegiatan` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`kegiatan` (
  `id_kegiatan` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `id_bidang` INT NULL,
  PRIMARY KEY (`id_kegiatan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`jenis_barang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`jenis_barang` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`jenis_barang` (
  `id_jenis` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id_jenis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`request` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`request` (
  `id_request` INT NOT NULL,
  `nama_req` VARCHAR(45) NULL,
  `tanggal` DATE NULL,
  `id_kegiatan` INT NULL,
  `id_barang` INT NULL,
  PRIMARY KEY (`id_request`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`history` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`history` (
  `id_history` INT NOT NULL,
  `id_barang` INT NULL,
  `tanggal` DATE NULL,
  `harga` DOUBLE NULL,
  `qty` INT NULL,
  `status` VARCHAR(45) NULL,
  `toko` VARCHAR(45) NULL,
  `id_request` INT NULL,
  PRIMARY KEY (`id_history`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`barang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`barang` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`barang` (
  `id_barang` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  `spek` VARCHAR(45) NULL,
  `satuan` VARCHAR(5) NULL,
  `tanggal` DATE NULL,
  `id_kegiatan` INT NULL,
  `id_jenis` INT NULL,
  PRIMARY KEY (`id_barang`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`gudang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`gudang` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`gudang` (
  `id_gudang` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gudang`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`spk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`spk` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`spk` (
  `id_spk` INT NOT NULL,
  `tanggal` VARCHAR(45) NULL,
  `id_barang` INT NULL,
  `id_kegiatan` INT NULL,
  `id_gudang` INT NULL,
  `tipe` VARCHAR(45) NULL,
  PRIMARY KEY (`id_spk`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`rusak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`rusak` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`rusak` (
  `id_rusak` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `id_barang` INT NULL,
  `keterangan` VARCHAR(100) NULL,
  PRIMARY KEY (`id_rusak`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aset_dkrth`.`perawatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aset_dkrth`.`perawatan` ;

CREATE TABLE IF NOT EXISTS `aset_dkrth`.`perawatan` (
  `id_perawatan` INT NOT NULL,
  `jadwal` DATE NULL,
  `id_barang` INT NULL,
  `keterangan` VARCHAR(100) NULL,
  PRIMARY KEY (`id_perawatan`) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
